version: '3.8'

services:
  langflow:
    image: langflowai/langflow:1.0.19
    container_name: langflow-code-helper
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
      - LANGFLOW_AUTO_LOGIN=true
      - LANGFLOW_SUPERUSER_API_KEY=clixen-langflow-api-key-2025
      - LANGFLOW_LOG_LEVEL=INFO
      - LANGFLOW_CACHE_TTL=3600
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - langflow-data:/app/data
      - ./langflow-flows:/app/flows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - clixen-network

  langflow-postgres:
    image: postgres:15
    container_name: langflow-postgres
    environment:
      - POSTGRES_USER=langflow
      - POSTGRES_PASSWORD=langflow123
      - POSTGRES_DB=langflow
    volumes:
      - langflow-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - clixen-network

volumes:
  langflow-data:
  langflow-postgres-data:

networks:
  clixen-network:
    driver: bridge