[build]
  # Build command with debugging and error handling
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build && ls -la dist/ && echo 'Build completed successfully'"
  
  # Publish directory (Vite builds to dist in frontend directory)
  publish = "frontend/dist"

[build.environment]
  # Node.js version - using Netlify default LTS version
  NODE_VERSION = "18"
  # Force npm usage instead of pnpm auto-detection
  NPM_FLAGS = "--legacy-peer-deps"
  # Secrets scanning configuration - exclude test files from scanning
  SECRETS_SCAN_OMIT_PATHS = "tests/**,test-*,**/*.test.*,**/*.spec.*,**/*.mjs,**/*.html"

# Enhanced Security Headers for Race Condition Protection
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Enable XSS filtering
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # Control referrer information leakage
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Restrict dangerous browser permissions
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Force HTTPS and prevent protocol downgrade attacks
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Enhanced Content Security Policy with stricter rules
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://zfbgdixbzezpxllkoyfc.supabase.co http://18.221.12.50:5678 https://*.netlify.app https://api.openai.com https://*.fly.dev wss://zfbgdixbzezpxllkoyfc.supabase.co; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:; frame-ancestors 'none'; form-action 'self'; base-uri 'self'"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes removed - using database-driven approach

# Functions removed - using database-driven approach


# Environment variables - SET THESE IN NETLIFY DASHBOARD
# Critical: These MUST be set or build will create empty/broken app
# Required variables:
# - VITE_SUPABASE_URL=https://zfbgdixbzezpxllkoyfc.supabase.co
# - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYmdkaXhiemV6cHhsbGtveWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDYzOTcsImV4cCI6MjA2ODYyMjM5N30.RIDf8tMNfcrVJsA_AhobZBU_H4gUHp6imiIFmzOFapw
# - VITE_N8N_API_URL=http://18.221.12.50:5678/api/v1
# - VITE_N8N_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODIxMTllNy1lYThlLTQyYzItYjgyNS1hY2ViNTk4OWQ2N2IiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU0MjYzMTM4fQ.VIvNOzeo2FtKUAgdVLcV9Xrg9XLC-xl11kp6yb_FraU
# Note: DO NOT set VITE_OPENAI_API_KEY (OpenAI is handled by Supabase Edge Functions)

# Function redirects removed - using database-driven approach

# SPA routing - redirect all non-API routes to index.html (MUST BE LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
