[build]
  # Build command - simple npm install and build with cache clear
  command = "npm install && npm run build"
  
  # Publish directory (Vite builds to dist by default)
  publish = "dist"

[build.environment]
  # Node.js version - using Netlify default LTS version
  NODE_VERSION = "18"
  # Force npm usage instead of pnpm auto-detection
  NPM_FLAGS = "--legacy-peer-deps"

# Security headers - CSP handled in HTML meta tag
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://zfbgdixbzezpxllkoyfc.supabase.co http://18.221.12.50:5678 https://*.netlify.app https://api.openai.com https://*.fly.dev ws: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:"f' data: https:"s:"https:"s:": https:""

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes removed - using database-driven approach

# Functions removed - using database-driven approach


# Frontend build environment variables (VITE_ prefix required for Vite)
[context.production.environment]
  # Frontend Vite Variables
  VITE_SUPABASE_URL = "https://zfbgdixbzezpxllkoyfc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYmdkaXhiemV6cHhsbGtveWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDYzOTcsImV4cCI6MjA2ODYyMjM5N30.RIDf8tMNfcrVJsA_AhobZBU_H4gUHp6imiIFmzOFapw"
  VITE_N8N_API_URL = "http://18.221.12.50:5678/api/v1"
  VITE_N8N_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODIxMTllNy1lYThlLTQyYzItYjgyNS1hY2ViNTk4OWQ2N2IiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU0MjYzMTM4fQ.VIvNOzeo2FtKUAgdVLcV9Xrg9XLC-xl11kp6yb_FraU"
  VITE_OPENAI_API_KEY = "your-openai-api-key-here"

[context.deploy-preview.environment]
  # Frontend Vite Variables
  VITE_SUPABASE_URL = "https://zfbgdixbzezpxllkoyfc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYmdkaXhiemV6cHhsbGtveWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDYzOTcsImV4cCI6MjA2ODYyMjM5N30.RIDf8tMNfcrVJsA_AhobZBU_H4gUHp6imiIFmzOFapw"
  VITE_N8N_API_URL = "http://18.221.12.50:5678/api/v1"
  VITE_N8N_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODIxMTllNy1lYThlLTQyYzItYjgyNS1hY2ViNTk4OWQ2N2IiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU0MjYzMTM4fQ.VIvNOzeo2FtKUAgdVLcV9Xrg9XLC-xl11kp6yb_FraU"
  VITE_OPENAI_API_KEY = "your-openai-api-key-here"

[context.branch-deploy.environment]
  # Frontend Vite Variables
  VITE_SUPABASE_URL = "https://zfbgdixbzezpxllkoyfc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYmdkaXhiemV6cHhsbGtveWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDYzOTcsImV4cCI6MjA2ODYyMjM5N10.RIDf8tMNfcrVJsA_AhobZBU_H4gUHp6imiIFmzOFapw"
  VITE_N8N_API_URL = "http://18.221.12.50:5678/api/v1"
  VITE_N8N_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODIxMTllNy1lYThlLTQyYzItYjgyNS1hY2ViNTk4OWQ2N2IiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU0MjYzMTM4fQ.VIvNOzeo2FtKUAgdVLcV9Xrg9XLC-xl11kp6yb_FraU"
  VITE_OPENAI_API_KEY = "your-openai-api-key-here"

# Function redirects removed - using database-driven approach

# SPA routing - redirect all non-API routes to index.html (MUST BE LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
