[build]
  # Build command - build the frontend workspace directly
  command = "npm --prefix frontend install && npm --prefix frontend run build"
  
  # Publish directory (Vite builds to dist in frontend directory)
  publish = "frontend/dist"

[build.environment]
  # Node.js version - using Netlify default LTS version
  NODE_VERSION = "18"
  # Force npm usage instead of pnpm auto-detection
  NPM_FLAGS = "--legacy-peer-deps"

# Security headers - CSP handled in HTML meta tag
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://zfbgdixbzezpxllkoyfc.supabase.co http://18.221.12.50:5678 https://*.netlify.app https://api.openai.com https://*.fly.dev ws: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes removed - using database-driven approach

# Functions removed - using database-driven approach


# Environment variables are now configured in Netlify Dashboard
# To configure: Site Settings > Environment Variables
# Required variables:
# - VITE_SUPABASE_URL 
# - VITE_SUPABASE_ANON_KEY
# - VITE_N8N_API_URL
# - VITE_N8N_API_KEY
# - VITE_OPENAI_API_KEY

# Function redirects removed - using database-driven approach

# SPA routing - redirect all non-API routes to index.html (MUST BE LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
