-- Migration: Add missing columns for workflow functionality
-- Date: August 13, 2025
-- Purpose: Fix critical database schema issues preventing workflow creation

-- Add missing webhook_url column to mvp_workflows table
ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS webhook_url TEXT;

-- Add execution tracking columns
ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS execution_count INTEGER DEFAULT 0;

ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS last_execution_at TIMESTAMP WITH TIME ZONE;

-- Add sync status columns for 2-way sync
ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS sync_status TEXT DEFAULT 'pending';

ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE mvp_workflows 
ADD COLUMN IF NOT EXISTS n8n_workflow_id TEXT;

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_mvp_workflows_user_id ON mvp_workflows(user_id);
CREATE INDEX IF NOT EXISTS idx_mvp_workflows_n8n_workflow_id ON mvp_workflows(n8n_workflow_id);
CREATE INDEX IF NOT EXISTS idx_mvp_workflows_sync_status ON mvp_workflows(sync_status);

-- Add comments for documentation
COMMENT ON COLUMN mvp_workflows.webhook_url IS 'The webhook URL generated by n8n for this workflow';
COMMENT ON COLUMN mvp_workflows.execution_count IS 'Number of times this workflow has been executed';
COMMENT ON COLUMN mvp_workflows.last_execution_at IS 'Timestamp of the last workflow execution';
COMMENT ON COLUMN mvp_workflows.sync_status IS 'Synchronization status between Supabase and n8n';
COMMENT ON COLUMN mvp_workflows.last_sync_at IS 'Timestamp of the last synchronization';
COMMENT ON COLUMN mvp_workflows.n8n_workflow_id IS 'The workflow ID in n8n system';

-- Verify the schema after migration
DO $$
BEGIN
    RAISE NOTICE 'Migration completed successfully';
    RAISE NOTICE 'mvp_workflows table now has all required columns for workflow functionality';
END $$;